use super::identity::{HostIdentity, parse_public_key};
use super::{
    ManagedSshHost, PRIVATE_MODE, PUBLIC_MODE, SshError, SshPaths, StateDirectory,
    maximum_managed_file_bytes, random_staging_name,
};
use std::ffi::OsString;
use std::fmt::Write as _;
use std::io::Write as _;
use std::net::{IpAddr, Ipv4Addr};

const CONFIG_NAME: &str = "config";
const KNOWN_HOSTS_NAME: &str = "known_hosts";

pub fn publish_openssh_files(
    paths: &SshPaths,
    identity: &HostIdentity,
    hosts: &[ManagedSshHost],
) -> Result<(), SshError> {
    validate_identity(paths, identity)?;
    let rendered = render_hosts(identity, hosts)?;
    let directory = StateDirectory::open(paths)?;
    directory
        .metadata("identity_ed25519", PRIVATE_MODE)?
        .ok_or(SshError::InvalidState("managed SSH private key is absent"))?;
    directory
        .metadata("identity_ed25519.pub", PUBLIC_MODE)?
        .ok_or(SshError::InvalidState("managed SSH public key is absent"))?;
    atomic_replace(
        &directory,
        KNOWN_HOSTS_NAME,
        rendered.known_hosts.as_bytes(),
    )?;
    atomic_replace(&directory, CONFIG_NAME, rendered.config.as_bytes())
}

pub fn readiness_ssh_args(paths: &SshPaths, alias: &str) -> Result<Vec<OsString>, SshError> {
    validate_alias(alias)?;
    Ok(vec![
        OsString::from("-F"),
        paths.config().as_std_path().as_os_str().to_owned(),
        OsString::from("-o"),
        OsString::from("BatchMode=yes"),
        OsString::from("-o"),
        OsString::from("ClearAllForwardings=yes"),
        OsString::from(alias),
        OsString::from("/usr/bin/true"),
    ])
}

fn validate_identity(paths: &SshPaths, identity: &HostIdentity) -> Result<(), SshError> {
    if identity.private_key != paths.private_key {
        return Err(SshError::InvalidState(
            "SSH config identity is outside managed state",
        ));
    }
    let parsed = parse_public_key(identity.public_key.as_bytes())?;
    if parsed.normalized != identity.public_key || parsed.fingerprint != identity.fingerprint {
        return Err(SshError::InvalidState(
            "SSH config identity metadata is inconsistent",
        ));
    }
    Ok(())
}

struct RenderedFiles {
    config: String,
    known_hosts: String,
}

fn render_hosts(
    identity: &HostIdentity,
    hosts: &[ManagedSshHost],
) -> Result<RenderedFiles, SshError> {
    let mut validated = Vec::with_capacity(hosts.len());
    for host in hosts {
        validate_alias(&host.active.alias)?;
        if host.active.host != IpAddr::V4(Ipv4Addr::LOCALHOST) || host.active.port == 0 {
            return Err(SshError::InvalidState(
                "managed SSH endpoint must be IPv4 loopback with a nonzero port",
            ));
        }
        if host.active.client_key_fingerprint != identity.fingerprint {
            return Err(SshError::InvalidState(
                "managed SSH client fingerprint is inconsistent",
            ));
        }
        let parsed_host_key = parse_public_key(host.host_public_key.as_bytes())?;
        if parsed_host_key.fingerprint != host.active.host_key_fingerprint {
            return Err(SshError::InvalidState(
                "managed SSH host fingerprint is inconsistent",
            ));
        }
        validated.push((host, parsed_host_key.normalized));
    }
    validated.sort_by(|left, right| left.0.active.alias.cmp(&right.0.active.alias));
    if validated
        .windows(2)
        .any(|pair| pair[0].0.active.alias == pair[1].0.active.alias)
    {
        return Err(SshError::InvalidState("managed SSH aliases are not unique"));
    }

    let identity_path = openssh_path(&identity.private_key)?;
    let known_hosts_path = openssh_path(&identity.private_key.with_file_name(KNOWN_HOSTS_NAME))?;
    let mut config = String::from("# Generated by Gas Can. Do not edit.\n");
    let mut known_hosts = String::new();
    for (host, public_key) in validated {
        writeln!(
            config,
            "\nHost {}\n    HostName 127.0.0.1\n    Port {}\n    User workspace\n    IdentityFile {}\n    IdentitiesOnly yes\n    HostKeyAlias {}\n    UserKnownHostsFile {}\n    StrictHostKeyChecking yes\n    ForwardAgent no",
            host.active.alias,
            host.active.port,
            identity_path,
            host.active.alias,
            known_hosts_path,
        )
        .map_err(|_| SshError::InvalidState("managed SSH config could not be rendered"))?;
        writeln!(
            known_hosts,
            "{},[127.0.0.1]:{} {}",
            host.active.alias, host.active.port, public_key
        )
        .map_err(|_| SshError::InvalidState("managed known-hosts could not be rendered"))?;
    }
    Ok(RenderedFiles {
        config,
        known_hosts,
    })
}

fn validate_alias(alias: &str) -> Result<(), SshError> {
    let Some(suffix) = alias.strip_prefix("gascan-") else {
        return Err(SshError::InvalidState("managed SSH alias is invalid"));
    };
    if suffix.is_empty()
        || alias.len() > 128
        || !suffix
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-')
        || suffix.starts_with('-')
        || suffix.ends_with('-')
        || suffix.contains("--")
    {
        return Err(SshError::InvalidState("managed SSH alias is invalid"));
    }
    Ok(())
}

fn openssh_path(path: &camino::Utf8Path) -> Result<String, SshError> {
    if path.as_str().bytes().any(|byte| byte.is_ascii_control()) {
        return Err(SshError::InvalidState(
            "managed SSH path cannot be represented in OpenSSH config",
        ));
    }
    let safe = path.as_str().bytes().all(|byte| {
        byte.is_ascii_alphanumeric() || matches!(byte, b'/' | b'.' | b'_' | b'-' | b':')
    });
    if safe {
        return Ok(path.as_str().to_owned());
    }
    let escaped = path
        .as_str()
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('%', "%%");
    Ok(format!("\"{escaped}\""))
}

fn atomic_replace(
    directory: &StateDirectory,
    target: &str,
    contents: &[u8],
) -> Result<(), SshError> {
    atomic_replace_with(directory, target, contents, || Ok(()))
}

fn atomic_replace_with<F>(
    directory: &StateDirectory,
    target: &str,
    contents: &[u8],
    before_publish: F,
) -> Result<(), SshError>
where
    F: FnOnce() -> Result<(), SshError>,
{
    if contents.len() as u64 > maximum_managed_file_bytes() {
        return Err(SshError::InvalidState(
            "generated managed SSH file is too large",
        ));
    }
    let previous = directory.metadata(target, PUBLIC_MODE)?;
    let staging = random_staging_name()?;
    let mut guard = StagingGuard::new(directory, &staging);
    {
        let mut file = directory.create_staging(&staging, PUBLIC_MODE)?;
        file.write_all(contents)
            .map_err(|error| SshError::io("write managed SSH staging file", error))?;
        file.flush()
            .map_err(|error| SshError::io("flush managed SSH staging file", error))?;
        file.sync_all()
            .map_err(|error| SshError::io("sync managed SSH staging file", error))?;
    }
    before_publish()?;
    if directory.metadata(target, PUBLIC_MODE)? != previous {
        return Err(SshError::InvalidState(
            "managed SSH target changed during replacement",
        ));
    }
    match previous {
        None => directory.rename_new(&staging, target)?,
        Some(_) => directory.rename_replace(&staging, target)?,
    }
    directory.sync()?;
    directory
        .metadata(target, PUBLIC_MODE)?
        .ok_or(SshError::InvalidState(
            "managed SSH file disappeared after replacement",
        ))?;
    guard.disarm();
    Ok(())
}

struct StagingGuard<'a> {
    directory: &'a StateDirectory,
    name: &'a str,
    armed: bool,
}

impl<'a> StagingGuard<'a> {
    const fn new(directory: &'a StateDirectory, name: &'a str) -> Self {
        Self {
            directory,
            name,
            armed: true,
        }
    }

    fn disarm(&mut self) {
        self.armed = false;
    }
}

impl Drop for StagingGuard<'_> {
    fn drop(&mut self) {
        if self.armed {
            self.directory.remove(self.name);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{
        PUBLIC_MODE, SshError, SshPaths, StateDirectory, atomic_replace, atomic_replace_with,
    };
    use std::fs;

    #[test]
    fn interrupted_atomic_replacement_preserves_previous_valid_file()
    -> Result<(), Box<dyn std::error::Error>> {
        let temp = tempfile::tempdir()?;
        let config_home = temp.path().canonicalize()?.join("xdg");
        let paths = SshPaths::for_environment(Some(config_home.as_os_str()), None)?;
        let directory = StateDirectory::open(&paths)?;
        atomic_replace(&directory, "config", b"previous\n")?;
        let result = atomic_replace_with(&directory, "config", b"replacement\n", || {
            Err(SshError::InvalidState("injected interruption"))
        });
        assert!(result.is_err());
        assert_eq!(fs::read(paths.config().as_std_path())?, b"previous\n");
        assert!(directory.metadata("config", PUBLIC_MODE)?.is_some());
        assert!(fs::read_dir(paths.directory().as_std_path())?.all(|entry| {
            entry.is_ok_and(|entry| !entry.file_name().to_string_lossy().starts_with('.'))
        }));
        Ok(())
    }
}
