use gascan_core::doctor::DoctorFacts;
use gascand::{DoctorState, SshPaths};
use std::os::unix::fs::PermissionsExt as _;
use std::time::Duration;

#[tokio::test]
async fn pending_doctor_callers_converge_on_one_completed_report() {
    let (state, completer) = DoctorState::pending();
    let left = tokio::spawn({
        let state = state.clone();
        async move { state.report().await }
    });
    let right = tokio::spawn({
        let state = state.clone();
        async move { state.report().await }
    });
    tokio::task::yield_now().await;
    assert!(!left.is_finished());
    assert!(!right.is_finished());
    let expected = DoctorFacts::all_supported_for_tests().into_report();
    completer.complete(expected.clone());
    assert_eq!(left.await.unwrap().checks, expected.checks);
    assert_eq!(right.await.unwrap().checks, expected.checks);
}

#[tokio::test]
async fn abandoned_doctor_collection_fails_closed() {
    let (state, completer) = DoctorState::pending();
    drop(completer);
    let report = state.report().await;
    assert!(report.checks.iter().all(|check| {
        check.status != gascan_core::doctor::DoctorStatus::Pass
            && check.detail.contains("was abandoned")
    }));
}

#[tokio::test(start_paused = true)]
async fn producer_timeout_is_cached_for_late_and_concurrent_callers() {
    let expected = DoctorFacts::all_supported_for_tests().into_report();
    let state = DoctorState::collect(Duration::from_secs(60), {
        let expected = expected.clone();
        async move {
            tokio::time::sleep(Duration::from_secs(61)).await;
            expected
        }
    });
    let left = tokio::spawn({
        let state = state.clone();
        async move { state.report().await }
    });
    let right = tokio::spawn({
        let state = state.clone();
        async move { state.report().await }
    });
    tokio::time::advance(Duration::from_secs(60)).await;
    tokio::task::yield_now().await;
    let left = left.await.unwrap();
    let right = right.await.unwrap();
    assert_eq!(left.checks, right.checks);
    assert!(
        left.checks
            .iter()
            .all(|check| check.detail.contains("exceeded its 60 second bound"))
    );

    tokio::time::advance(Duration::from_secs(2)).await;
    let late = state.report().await;
    assert_eq!(late.checks, left.checks);
}

#[test]
fn ssh_doctor_facts_are_release_blocking_and_stably_identified() {
    let report = DoctorFacts::all_supported_for_tests().into_report();
    for id in [
        "ssh.client",
        "ssh.identity",
        "ssh.config",
        "ssh.native_publish",
    ] {
        let check = report.check(id).unwrap();
        assert_eq!(
            check.status,
            gascan_core::doctor::DoctorStatus::Pass,
            "{id}"
        );
        assert!(!check.detail.is_empty(), "{id}");
        assert!(!check.remedy.is_empty(), "{id}");
    }
}

#[tokio::test]
async fn ssh_doctor_accepts_absent_managed_state_without_creating_it()
-> Result<(), Box<dyn std::error::Error>> {
    let temp = tempfile::tempdir()?;
    let home = temp.path().join("home");
    std::fs::create_dir(&home)?;
    std::fs::set_permissions(&home, std::fs::Permissions::from_mode(0o700))?;
    let home = home.canonicalize()?;
    let paths = SshPaths::for_environment(None, Some(home.as_os_str()))?;
    let client = temp.path().join("ssh");
    std::fs::write(&client, "#!/bin/sh\nexit 0\n")?;
    std::fs::set_permissions(&client, std::fs::Permissions::from_mode(0o755))?;

    let facts = gascand::ssh_doctor_facts_for_paths(&paths, &client, true).await;

    assert_eq!(facts.client.status, gascan_core::doctor::DoctorStatus::Pass);
    assert_eq!(
        facts.identity.status,
        gascan_core::doctor::DoctorStatus::Pass,
        "{}",
        facts.identity.detail
    );
    assert_eq!(
        facts.config.status,
        gascan_core::doctor::DoctorStatus::Pass,
        "{}",
        facts.config.detail
    );
    assert_eq!(
        facts.native_publish.status,
        gascan_core::doctor::DoctorStatus::Pass
    );
    assert!(!paths.directory().exists());
    Ok(())
}

#[tokio::test]
async fn ssh_doctor_parses_the_generated_config_with_exact_discrete_arguments()
-> Result<(), Box<dyn std::error::Error>> {
    let temp = tempfile::tempdir()?;
    let home = temp.path().join("home");
    let directory = home.join(".config/gascan/ssh");
    std::fs::create_dir_all(&directory)?;
    for path in [
        home.clone(),
        home.join(".config"),
        home.join(".config/gascan"),
        directory.clone(),
    ] {
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o700))?;
    }
    let home = home.canonicalize()?;
    let directory = home.join(".config/gascan/ssh");
    let config = directory.join("config");
    std::fs::write(&config, "# Generated by Gas Can. Do not edit.\n")?;
    std::fs::set_permissions(&config, std::fs::Permissions::from_mode(0o644))?;
    let capture = temp.path().join("ssh.args");
    let client = temp.path().join("ssh");
    std::fs::write(
        &client,
        format!(
            "#!/bin/sh\nprintf '%s\\n' \"$@\" >{}\nexit 0\n",
            capture.display()
        ),
    )?;
    std::fs::set_permissions(&client, std::fs::Permissions::from_mode(0o755))?;
    let paths = SshPaths::for_environment(None, Some(home.as_os_str()))?;

    let facts = gascand::ssh_doctor_facts_for_paths(&paths, &client, true).await;

    assert_eq!(facts.config.status, gascan_core::doctor::DoctorStatus::Pass);
    assert_eq!(
        std::fs::read_to_string(capture)?,
        format!("-G\n-F\n{}\ngascan-doctor\n", config.display())
    );
    Ok(())
}

#[tokio::test]
async fn ssh_doctor_fails_closed_for_partial_identity_and_rejected_generated_config()
-> Result<(), Box<dyn std::error::Error>> {
    let temp = tempfile::tempdir()?;
    let home = temp.path().join("home");
    let directory = home.join(".config/gascan/ssh");
    std::fs::create_dir_all(&directory)?;
    for path in [
        home.clone(),
        home.join(".config"),
        home.join(".config/gascan"),
        directory.clone(),
    ] {
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o700))?;
    }
    let home = home.canonicalize()?;
    let directory = home.join(".config/gascan/ssh");
    std::fs::write(directory.join("identity_ed25519"), "partial")?;
    std::fs::set_permissions(
        directory.join("identity_ed25519"),
        std::fs::Permissions::from_mode(0o600),
    )?;
    std::fs::write(directory.join("config"), "Host broken\n")?;
    std::fs::set_permissions(
        directory.join("config"),
        std::fs::Permissions::from_mode(0o644),
    )?;
    let paths = SshPaths::for_environment(None, Some(home.as_os_str()))?;
    let client = temp.path().join("ssh");
    std::fs::write(&client, "#!/bin/sh\nexit 42\n")?;
    std::fs::set_permissions(&client, std::fs::Permissions::from_mode(0o755))?;

    let facts = gascand::ssh_doctor_facts_for_paths(&paths, &client, false).await;

    assert_eq!(
        facts.identity.status,
        gascan_core::doctor::DoctorStatus::Fail
    );
    assert!(facts.identity.detail.contains(paths.private_key().as_str()));
    assert_eq!(facts.config.status, gascan_core::doctor::DoctorStatus::Fail);
    assert!(facts.config.detail.contains(paths.config().as_str()));
    assert_eq!(
        facts.native_publish.status,
        gascan_core::doctor::DoctorStatus::Fail
    );
    Ok(())
}
